name: CI/CD for teii Package

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "test-package" and "build-and-publish-package"

  test-package:
    # The type of runners that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os: [ubuntu-20.04, ubuntu-22.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up python version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: py${{ matrix.python-version }}

    # Installs tox
    - name: Install tox
      run: |
        pip install tox==4.14.2

    # Runs tox
    - name: Run flake8, mypy and pytest with tox
      run: |
        tox -e py

  build:
    # The type of runners that the job will run on
    runs-on: ${{ matrix.os }}
    needs: test-package

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up python version
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Builds the package
    - name: Build package
      run: |
        pip install setuptools wheel
        python setup.py bdist_wheel
